language: generic
sudo: required
before_script:
- sudo apt-get remove --purge docker-engine
- curl -fsSL https://get.docker.com/ | sh
- sudo curl -L -o /usr/local/bin/opctl https://github.com/opctl/cli/releases/download/0.1.4/opctl-linux-x86_64
- sudo chmod +x /usr/local/bin/opctl
services:
- docker
script:
- opctl run -a GIT_BRANCH=$TRAVIS_BRANCH release
env:
  global:
    secure: Ar6mYU0kIjOEue623L6wPmqq3xyP4F0Vuvq9vzk1BGC8iyJRTYGRutHbJXHD/oyQo9naTA6Gn5qHGJhHYVUZa9/cMlgsXlkFyIFwFYAHYTdW4DQjRI+c+HAdThNbr/rvpuh35MECQgEYVsSz0JV2OSnN7oa7kPHLuPWdNemAK/TysOPs8iSp9WxjL1Dn1NrzRzYiZ8GzDzb1oTgiBmCAh/L5k4TXg5hdO6VpHZpu6pj28j0Yet2lO2FNMaRrqoPCyxfMiiNDKNDvE6M4r2fLHhiH/M8mraAudPJ1lPrRgQ2LtrWQaGb54SXxv2AypX/t0RATiESzz2jRTrwgwXcFS8+petAgj9ydMOnCbmDiM9+iu3Ht9TuPZ+wi1imRHSCTxKbE3g2DbSsJdxKQgGFNOB1CSt+u14s6ze6WDIfGws2rXVuZpbrOw1CDaEUfvG5PhiToiKJyfmg0vrrexu1FXGGqAuRLHorMFO6U2X/csM4qWP9L6VQQ7M4+UMsAj6LYFdz6Sfzirmi4NaQanHAXAGgjshkYQ5OHCcy+TnwvjcZlP0f2/vp4ya+rsMutvIEmk9hu2/TJIRmSb7pMrm5sUiMSXWIKOPA/axTlZ1hr7q39jN1SZ0dVdOWzBlz04xyS8aKtpAlctCtBlcMLZKk0Qf/LSA0C9I4+fy4R2TJtRGA=
