// This file was generated by counterfeiter
package main

import "sync"

type fakeExiter struct {
  ExitStub         func(code int)
  exitMutex        sync.RWMutex
  exitArgsForCall  []struct {
    code int
  }
  invocations      map[string][][]interface{}
  invocationsMutex sync.RWMutex
}

func (fake *fakeExiter) Exit(code int) {
  fake.exitMutex.Lock()
  fake.exitArgsForCall = append(fake.exitArgsForCall, struct {
    code int
  }{code})
  fake.recordInvocation("Exit", []interface{}{code})
  fake.exitMutex.Unlock()
  if fake.ExitStub != nil {
    fake.ExitStub(code)
  }
}

func (fake *fakeExiter) ExitCallCount() int {
  fake.exitMutex.RLock()
  defer fake.exitMutex.RUnlock()
  return len(fake.exitArgsForCall)
}

func (fake *fakeExiter) ExitArgsForCall(i int) int {
  fake.exitMutex.RLock()
  defer fake.exitMutex.RUnlock()
  return fake.exitArgsForCall[i].code
}

func (fake *fakeExiter) Invocations() map[string][][]interface{} {
  fake.invocationsMutex.RLock()
  defer fake.invocationsMutex.RUnlock()
  fake.exitMutex.RLock()
  defer fake.exitMutex.RUnlock()
  return fake.invocations
}

func (fake *fakeExiter) recordInvocation(key string, args []interface{}) {
  fake.invocationsMutex.Lock()
  defer fake.invocationsMutex.Unlock()
  if fake.invocations == nil {
    fake.invocations = map[string][][]interface{}{}
  }
  if fake.invocations[key] == nil {
    fake.invocations[key] = [][]interface{}{}
  }
  fake.invocations[key] = append(fake.invocations[key], args)
}
