// This file was generated by counterfeiter
package main

import (
  "sync"
)

type fakeExiter struct {
  ExitStub         func(req exitReq)
  exitMutex        sync.RWMutex
  exitArgsForCall  []struct {
    req exitReq
  }
  invocations      map[string][][]interface{}
  invocationsMutex sync.RWMutex
}

func (fake *fakeExiter) Exit(req exitReq) {
  fake.exitMutex.Lock()
  fake.exitArgsForCall = append(fake.exitArgsForCall, struct {
    req exitReq
  }{req})
  fake.recordInvocation("Exit", []interface{}{req})
  fake.exitMutex.Unlock()
  if fake.ExitStub != nil {
    fake.ExitStub(req)
  }
}

func (fake *fakeExiter) ExitCallCount() int {
  fake.exitMutex.RLock()
  defer fake.exitMutex.RUnlock()
  return len(fake.exitArgsForCall)
}

func (fake *fakeExiter) ExitArgsForCall(i int) exitReq {
  fake.exitMutex.RLock()
  defer fake.exitMutex.RUnlock()
  return fake.exitArgsForCall[i].req
}

func (fake *fakeExiter) Invocations() map[string][][]interface{} {
  fake.invocationsMutex.RLock()
  defer fake.invocationsMutex.RUnlock()
  fake.exitMutex.RLock()
  defer fake.exitMutex.RUnlock()
  return fake.invocations
}

func (fake *fakeExiter) recordInvocation(key string, args []interface{}) {
  fake.invocationsMutex.Lock()
  defer fake.invocationsMutex.Unlock()
  if fake.invocations == nil {
    fake.invocations = map[string][][]interface{}{}
  }
  if fake.invocations[key] == nil {
    fake.invocations[key] = [][]interface{}{}
  }
  fake.invocations[key] = append(fake.invocations[key], args)
}
