// This file was generated by counterfeiter
package main

import (
	"sync"

	"github.com/opctl/sdk-for-golang/sdk"
)

type fakeCompositionRoot struct {
	SdkStub        func() sdk.Client
	sdkMutex       sync.RWMutex
	sdkArgsForCall []struct{}
	sdkReturns     struct {
		result1 sdk.Client
	}
}

func (fake *fakeCompositionRoot) Sdk() sdk.Client {
	fake.sdkMutex.Lock()
	fake.sdkArgsForCall = append(fake.sdkArgsForCall, struct{}{})
	fake.sdkMutex.Unlock()
	if fake.SdkStub != nil {
		return fake.SdkStub()
	} else {
		return fake.sdkReturns.result1
	}
}

func (fake *fakeCompositionRoot) SdkCallCount() int {
	fake.sdkMutex.RLock()
	defer fake.sdkMutex.RUnlock()
	return len(fake.sdkArgsForCall)
}

func (fake *fakeCompositionRoot) SdkReturns(result1 sdk.Client) {
	fake.SdkStub = nil
	fake.sdkReturns = struct {
		result1 sdk.Client
	}{result1}
}
