version: "2"
services:
  build-bin-windows:
    extends:
      service: go-build
      file: ../.common/docker-compose.yml
    environment:
      - GOOS=windows
      - OUTPUT_FILE_EXTENSION=.exe
    network_mode: none
