version: "2"
services:
  publish-coverage-to-codecov:
    extends:
      service: src
      file: ../.common/docker-compose.yml
    build: ./
    environment:
      - CODECOV_TOKEN
      - GIT_BRANCH
    entrypoint: |
      sh -c "
        # generate aggregate coverage profile
        cp overalls.coverprofile coverage.txt

        # strip fakes from coverage profile
        sed -i '/fake/d' coverage.txt && \

        curl -s https://codecov.io/bash | bash -s
      "
