version: "2"
services:
  src:
    image: scratch
    volumes:
      - ../../../:/golang/src/github.com/open-devops/cli
    working_dir: /golang/src/github.com/open-devops/cli
  go:
    extends:
      service: src
    build: ./
    network_mode: host
    environment:
      - GOPATH=/golang
      - GOARCH=amd64
      - CGO_ENABLED=0
  go-build:
    extends:
      service: go
    environment:
      - PATH_TO_TMP_DIR=.dev-op-spec/ops/.tmp/build
    entrypoint: .dev-op-spec/ops/.common/go-build-entrypoint.sh
