version: "2"
services:
  src:
    image: scratch
    volumes:
      - ../../:/go/src/github.com/opspec-io/cli
    working_dir: /go/src/github.com/opspec-io/cli
  go:
    extends:
      service: src
    build: ./
    environment:
      - "GOARCH=amd64"
      - CGO_ENABLED=0
  go-build:
    extends:
      service: go
    entrypoint: |
      sh -c "
        go get ./... && \
        go build -a -o tmp/opctl-$${GOOS}-x86_64$${OUTPUT_FILE_EXTENSION}
      "
