version: "2"
services:
  src:
    image: scratch
    volumes:
      - ../../:/golang/src/github.com/opctl/cli
    working_dir: /golang/src/github.com/opctl/cli
  go:
    extends:
      service: src
    build: ./
    environment:
      - GOPATH=/golang
      - "GOARCH=amd64"
      - CGO_ENABLED=0
  go-build:
    extends:
      service: go
    entrypoint: .opspec/.common/go-build-entrypoint.sh
