version: "2"
services:
  working_dir:
    image: scratch
    volumes:
      - ../../:/go/src/github.com/opspec-io/cli
    working_dir: /go/src/github.com/opspec-io/cli
  go:
    extends:
      service: working_dir
    build: ./
    environment:
      - GOARCH=amd64
      - GOOS=linux
  go-build:
    extends:
      service: go
    entrypoint: |
      sh -c "
        go build -a -o tmp/opctl-$${GOOS}-x86_64$${OUTPUT_FILE_EXTENSION}
      "
    environment:
      - CGO_ENABLED=0
